ALERTS_WEBHOOK_URL=https://discord.com/api/webhooks/1484975771171688578/38VHSEkapOLUPBUlMk8j7Vn3qFrS71UF7YVguQT8rWKHdKwx342TZrrfD9DApCswGft1
LOGS_WEBHOOK_URL=https://discord.com/api/webhooks/1484976000642318439/aLoYoeKHMvtPgueK4qArTvuAF4rzhMUHCdsqxJnOU5prj8NmcrWwTJhBeM7s0lBMFWfW
