#!/bin/bash
# PreToolUse hook: enforce shell-generated handoff timestamps.
#
# WHY: session-handoff.md prescribes a draft->rename flow so the timestamp is
# generated by the shell ($(TZ=America/New_York date ...)) and NEVER typed by the
# model. That flow is guidance-only, and the model keeps bypassing it by writing
# straight to a timestamped path — producing filenames hours/days off (the harness
# injects the date as UTC, so an evening-EDT session confabulates tomorrow's date).
# This hook makes bypass impossible: it rejects any Write/Edit/Bash that puts a
# HANDOFF filename with LITERAL date digits on disk. The sanctioned flow has no
# literal digits (they live in a $(date) subshell), so it passes untouched.
#
# Ref: ~/.claude/commands/session-handoff.md:23 (draft path) and :26 (mv + TZ format).
# Exit 2 = block (Claude sees stderr). Exit 0 = allow. (Geoff's lesson: block=2, reason->stderr.)

if ! command -v python3 >/dev/null 2>&1; then
  # Fail closed on parse infra loss, per house convention.
  echo "BLOCKED: python3 not found — cannot parse handoff-timestamp-guard input." >&2
  exit 2
fi

INPUT=$(cat)

# A literal-timestamped handoff filename: HANDOFF-...YYYY-MM-DD...md with the digits
# written out (not a $(date) subshell). This is the fingerprint of the bug.
TS_PATTERN='HANDOFF-[^/ \t]*[0-9]{4}-[0-9]{2}-[0-9]{2}[^/ \t]*\.md'

VERDICT=$(echo "$INPUT" | python3 -c "
import sys, json, re
try:
    d = json.load(sys.stdin)
    tool = d.get('tool_name', '')
    ti = d.get('tool_input', {})
    ts_bare = r'$TS_PATTERN'
    ts = re.compile(ts_bare)
    if tool in ('Write', 'Edit'):
        if ts.search(ti.get('file_path', '') or ''):
            print('block:tool')
    elif tool == 'Bash':
        cmd = ti.get('command', '') or ''
        # Only look at the WRITE TARGET of an actual write op, not any co-occurrence
        # of a write-op token and a HANDOFF filename anywhere in the command text.
        # This avoids false positives from e.g. '2>&1' on a read-only find/grep, or
        # a HANDOFF filename appearing only as a read-only argument (find -newer,
        # cat, diff, grep -l, ls).
        blocked = False
        # Redirects: '>' or '>>' (optionally preceded by an fd digit, e.g. '2>')
        # whose target (next whitespace-delimited token) is a timestamped HANDOFF path.
        for m in re.finditer(r'[0-9]?>{1,2}\s*(\S+)', cmd):
            if ts.fullmatch(m.group(1).strip('\'\"')) or ts.search(m.group(1)):
                blocked = True
                break
        # cp/mv/tee: the DESTINATION (last non-flag token) of that command clause
        # is a timestamped HANDOFF path. Split on shell separators to scope each
        # clause, then check only the trailing argument, not the whole clause.
        if not blocked:
            for clause in re.split(r'&&|\|\||;|\|', cmd):
                cm = re.search(r'\b(cp|mv|tee)\b(.*)$', clause)
                if not cm:
                    continue
                args = [a for a in cm.group(2).split() if not a.startswith('-')]
                if args and ts.search(args[-1]):
                    blocked = True
                    break
        if blocked:
            print('block:bash')
except Exception:
    # Never crash the tool call over a parse hiccup; let it through (fail-open on
    # unknown shapes — this hook only ever ADDS a restriction, sensitive-file hook
    # still fails closed separately).
    pass
" 2>/dev/null)

if [ -n "$VERDICT" ]; then
  cat >&2 <<'EOF'
BLOCKED: don't write a HANDOFF filename with a typed-in timestamp — that is the
exact source of the wrong-timestamp bug (the model's date is UTC, not EDT).

Use the sanctioned flow so the SHELL stamps the time (session-handoff.md):
  1. Write the body to the fixed draft path:  $(pwd)/handoffs/.HANDOFF-draft.md
  2. Rename with a shell-generated timestamp (no digits typed by you):
     mkdir -p "$PWD/handoffs" && f="$PWD/handoffs/HANDOFF-<name>-$(TZ=America/New_York date '+%Y-%m-%d-%H%M').md" && mv "$PWD/handoffs/.HANDOFF-draft.md" "$f" && ls -la "$f"
EOF
  exit 2
fi

exit 0
