#!/bin/bash
# PreToolUse hook: enforce shell-generated handoff timestamps.
#
# WHY: session-handoff.md prescribes a draft->rename flow so the timestamp is
# generated by the shell ($(TZ=America/New_York date ...)) and NEVER typed by the
# model. That flow is guidance-only, and the model keeps bypassing it by writing
# straight to a timestamped path — producing filenames hours/days off (the harness
# injects the date as UTC, so an evening-EDT session confabulates tomorrow's date).
# This hook makes bypass impossible: it rejects any Write/Edit/Bash that puts a
# HANDOFF filename with LITERAL date digits on disk. The sanctioned flow has no
# literal digits (they live in a $(date) subshell), so it passes untouched.
#
# Ref: ~/.claude/commands/session-handoff.md:23 (draft path) and :26 (mv + TZ format).
# Exit 2 = block (Claude sees stderr). Exit 0 = allow. (the user's lesson: block=2, reason->stderr.)

if ! command -v python3 >/dev/null 2>&1; then
  # Fail closed on parse infra loss, per house convention.
  echo "BLOCKED: python3 not found — cannot parse handoff-timestamp-guard input." >&2
  exit 2
fi

INPUT=$(cat)

# A literal-timestamped handoff filename: HANDOFF-...YYYY-MM-DD...md with the digits
# written out (not a $(date) subshell). This is the fingerprint of the bug.
TS_PATTERN='HANDOFF-[^/]*[0-9]{4}-[0-9]{2}-[0-9]{2}[^/]*\.md'
# Bash create/write operators that would put such a name on disk. A bare read
# (cat/ls/grep/find/git) or the sanctioned $(date) mv will NOT match this.
WRITE_OP='(>>?|\b(tee|cp|mv)\b)'

VERDICT=$(echo "$INPUT" | python3 -c "
import sys, json, re
try:
    d = json.load(sys.stdin)
    tool = d.get('tool_name', '')
    ti = d.get('tool_input', {})
    ts = re.compile(r'$TS_PATTERN')
    if tool in ('Write', 'Edit'):
        if ts.search(ti.get('file_path', '') or ''):
            print('block:tool')
    elif tool == 'Bash':
        cmd = ti.get('command', '') or ''
        # Block only if it both names a literal-timestamped handoff AND writes to it.
        if ts.search(cmd) and re.search(r'''$WRITE_OP''', cmd):
            print('block:bash')
except Exception:
    # Never crash the tool call over a parse hiccup; let it through (fail-open on
    # unknown shapes — this hook only ever ADDS a restriction, sensitive-file hook
    # still fails closed separately).
    pass
" 2>/dev/null)

if [ -n "$VERDICT" ]; then
  cat >&2 <<'EOF'
BLOCKED: don't write a HANDOFF filename with a typed-in timestamp — that is the
exact source of the wrong-timestamp bug (the model's date is UTC, not EDT).

Use the sanctioned flow so the SHELL stamps the time (session-handoff.md):
  1. Write the body to the fixed draft path:  $(pwd)/handoffs/.HANDOFF-draft.md
  2. Rename with a shell-generated timestamp (no digits typed by you):
     mkdir -p "$PWD/handoffs" && f="$PWD/handoffs/HANDOFF-<name>-$(TZ=America/New_York date '+%Y-%m-%d-%H%M').md" && mv "$PWD/handoffs/.HANDOFF-draft.md" "$f" && ls -la "$f"
EOF
  exit 2
fi

exit 0
